### ISSUE TITLE
您好，我在用 stream 模块的时候报错：ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by Mindsetimportant** [caojx-git/learn#1]
报错信息：
[root@localhost conf]# ssh -p 80  root@192.168.0.252 
ssh_exchange_identification: Connection closed by remote 

配置：
stream { 
        upstream ssh {
                server 192.168.0.252:22;
        }
        server { 
                listen 80;
                proxy_pass ssh;
                proxy_connect_timeout 1h;
                proxy_timeout 1h;
        }
}

**Comment by caojx-git** [comment]
你好，我今天又安装试了一下，可以的，按照我的文章操作试一遍，请确保nginx启动正确，我用的80端口，你可以试一下别的端口，不行的话可以尝试关闭一下防火墙（不要在生产环境这么做）
https://github.com/caojx-git/learn/blob/master/notes/nginx/nginx%E4%BD%BF%E7%94%A8stream%E6%A8%A1%E5%9D%97%E5%81%9Assh%E8%BD%AC%E5%8F%91.md

**Comment by caojx-git** [comment]
user  root;
worker_processes  1;

events {
    worker_connections  1024;
}

stream {
    upstream ssh {
        server 目标主机ip:22;
    }
    server {
        listen 监听端口;
        proxy_pass ssh;
        proxy_connect_timeout 1h;
        proxy_timeout 1h;
    }
}
